name: CI
on:
  pull-request:
    branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node2v1
        with:
          node-version: "12.x"
      - run: npm CI
      - run: npm format:check
      - run: npm test -- --coverage
        env: 
          CI: true

       